name: gg_admin
description: "An Admin sided application for Glitch Goods Business"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.1
  iconify_flutter: ^0.0.7
  uuid: ^4.5.1
  intl: ^0.20.2
  carousel_slider_plus: ^7.1.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true